### PR TITLE
Only keep necessary assets.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- As per #6 we're now deploying dev build of umami, which is large, perserves `yarn` cache and additionally yields the following log entry:

```
Sep 22 23:45:58 npm[2988041]: - warn "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
```

## Solution

- Prepare the output dir as per https://github.com/umami-software/umami/blob/master/Dockerfile

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@orhtej2 would you like to maintain Umami?

**Comment by orhtej2** [comment]
@ericgaspar sure, why not.

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
Bumped to 2.8.0, will merge with next upstream release

**Comment by ericgaspar** [comment]
And you can remove my name from the manifest

**Pull request merged**
