### PR TITLE
Disable umami and next.js telemetry.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- Umami is publishing telemetry.

## Solution

- Disable telemetry for both `umami` and `next.js`

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme

**Comment by ericgaspar** [comment]
is the `.env` setting not enough?

**Comment by orhtej2** [comment]
> is the `.env` setting not enough?

[`DISABLE_TELEMETRY`](https://umami.is/docs/environment-variables) is `umami` setting, [`NEXT_TELEMETRY_DISABLED`](https://nextjs.org/telemetry) is `next.js` setting.

**Comment by orhtej2** [comment]
(and judging from [`Dockerfile`](https://github.com/umami-software/umami/blob/master/Dockerfile) `next.js` publishes some telemetry during build as well)

**Pull request merged**
